### PR TITLE
[15.0][ADD] repair_type_security

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Glue module so access to repair types is based on groups defined in repair_security instead of using stock goups

cc @ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
Code review LGTM, maybe auto_install?

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Comment by AaronHForgeFlow** [comment]
> Code review LGTM, maybe auto_install?

Yes, I think it is a good point, I just did the change

**Review by LoisRForgeFlow — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
