### PR TITLE
[16.0][MIG] repair_stock_move

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Standard Migration to 16.0

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@DavidJForgeFlow could you include this commit https://github.com/OCA/repair/pull/15/commits/30fe6ddfee9aec6b9dcfeea23938fe4298c513d9 here?

**Comment by JordiBForgeFlow** [comment]
@DavidJForgeFlow can you attend to the comment from @LoisRForgeFlow ?

**Comment by LoisRForgeFlow** [comment]
> @DavidJForgeFlow could you include this commit [30fe6dd](https://github.com/OCA/repair/commit/30fe6ddfee9aec6b9dcfeea23938fe4298c513d9) here?

@DavidJForgeFlow could you cherry pick https://github.com/OCA/repair/commit/30fe6ddfee9aec6b9dcfeea23938fe4298c513d9. I still cannot see it included.

Thanks!

**Comment by DavidJForgeFlow** [comment]
> > @DavidJForgeFlow could you include this commit [30fe6dd](https://github.com/OCA/repair/commit/30fe6ddfee9aec6b9dcfeea23938fe4298c513d9) here?
> 
> @DavidJForgeFlow could you cherry pick [30fe6dd](https://github.com/OCA/repair/commit/30fe6ddfee9aec6b9dcfeea23938fe4298c513d9). I still cannot see it included.
> 
> Thanks!

Done! Sorry for the delay!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

/ocabot merge nobump

**Pull request merged**
