### PR TITLE
[16.0][MIG] repair_refurbish: Migration to 16.0

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
Migration to 16.0

[ForgeFlow](https://github.com/ForgeFlow)

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by LoisRForgeFlow** [comment]
@AlexPForgeFlow can you add the changes done here https://github.com/OCA/repair/pull/24 ?

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

/ocabot merge nobump

**Pull request merged**
