### PR TITLE
[17.0][ADD] repair_quality_control: New module repair_quality_control

### PR DESCRIPTION
**Pull request by peluko00**
**_New module repair_quality_control_**
This module allows to create quality control inspections from repair order
when that one is done. One repair order is linked to many different inspections.

cc https://github.com/APSL 155857
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

[Grabación de pantalla desde 2024-09-13 16-28-21.webm](https://github.com/user-attachments/assets/3940320a-a2e3-417b-80b3-159ffb47263e)

### CODE REVIEW

**Comment by miquelalzanillas** [comment]
Good work. The workflow looks perfect.

Seems there is an error while creating inspection order from button.

`KeyError: '%s'`

**Comment by peluko00** [comment]
> Good work. The workflow looks perfect.
> 
> Seems there is an error while creating inspection order from button.
> 
> `KeyError: '%s'`

Thanks for the feedback, fixed!

**Review by BernatObrador — APPROVED** [review]
LGTM, works as intended, tested in runboat.

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by miquelalzanillas — APPROVED** [review]

**Comment by peluko00** [comment]
@LoisRForgeFlow can you review please

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM :+1:

**Pull request merged**
