### PR TITLE
[17.0][ADD] base_repair_config: Moved from manufacture

### PR DESCRIPTION
**Pull request by ppyczko**
Module moved from [OCA/manufacture](https://github.com/OCA/manufacture/tree/13.0/base_repair_config) to OCA/repair and migrated from version 13.0 to version 17.0

cc https://github.com/APSL 163957

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @BernatObrador please review

### CODE REVIEW

**Review by peluko00 — APPROVED** [review]
LGTM, code review and tested in runboat

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
