### PR TITLE
[17.0][ADD] repair_timesheet: New module repair_timesheet

### PR DESCRIPTION
**Pull request by ppyczko**
This module integrates timesheet tracking with repair orders. It adds a "Timesheets" tab to the repair order form, allowing users to log and track the time spent on each repair through timesheet entries. 

cc https://github.com/APSL 161660

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @BernatObrador please review

### CODE REVIEW

**Review by BernatObrador — APPROVED** [review]
LGTM Code review and tested in runboat

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat and code review

**Review by peluko00 — APPROVED** [review]
LGTM, code review and tested in runboat

**Comment by ppyczko** [comment]
Hi @LoisRForgeFlow, could you please review this module when you have a moment? Thank you!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
