### PR TITLE
[16.0][MIG] repair_type_refurbish: Migration to 16.0

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
Migration to 16.0

[ForgeFlow](https://github.com/ForgeFlow)

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@AlexPForgeFlow Can you rebase this one?

**Comment by AlexPForgeFlow** [comment]
> @AlexPForgeFlow Can you rebase this one?

Done!

**Comment by LoisRForgeFlow** [comment]
Thanks!

I see, there is a dependency waiting:

- https://github.com/OCA/repair/pull/23

**Review by LoisRForgeFlow — APPROVED** [review]
Standard migration

/ocabot migration repair_type_refurbish

/ocabot merge nobump

**Pull request merged**
