### PR TITLE
[17.0][MIG] repair_stock: Migration to 17.0

### PR DESCRIPTION
**Pull request by ppyczko**
Module migrated to version 17.0

cc https://github.com/APSL 162608

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @BernatObrador please review

- Issue #36

Due to the changes made in the Odoo core, the 'repair.line' model has been replaced by a 'stock.move' inheritance. Refer to: https://github.com/odoo/odoo/commit/eaa6e1a08c3d2cdcb558689523e5bd332978f5e4#diff-d0a358caec30d24192fe20d0198069c9749f8297fc7f0c153a792b5ffdb8ed35

Consequently, the OCA module repair_stock_move is no longer required. As a result, the dependency on repair_stock_move has been removed, and the module and tests have been adapted to accommodate this update.

### CODE REVIEW

**Review by peluko00 — APPROVED** [review]
LGTM

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Comment by BernatObrador** [comment]
Hi @ppyczko, please squash administrative commits!

**Comment by ppyczko** [comment]
> Hi @ppyczko, please squash administrative commits!

Done, thanks @BernatObrador!

**Review by BernatObrador — APPROVED** [review]
LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks for the contribution, LGTM :+1:

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
