### PR TITLE
[15.0] [MIG] repair_refurbish

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Comment by LoisRForgeFlow** [comment]
First module EVER in this repository :stuck_out_tongue_closed_eyes: 

/ocabot merge nobump

**Comment by AaronHForgeFlow** [comment]
> First module EVER in this repository stuck_out_tongue_closed_eyes

Achievement unlocked :)

**Pull request merged**
