### PR TITLE
[15.0][ADD] repair_stock_move_restrict_lot: Assign lot on stock move creation. 

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
This is a new module. It is needed when using repair_stock_move and using lots. Otherwise in the_action_assign it may reserve the incorrect quant and then and error is raised when unreserving the quant: https://github.com/odoo/odoo/blob/15.0/addons/stock/models/stock_move_line.py#L388

Steps to reproduce. Create a product tracked with serial number and create multiple quants for various serials. It may happen that the reservation is done in the incorrect serial.  See test case added for reference

Without this module you may get this error:

```
  File "/opt/odoo/auto/addons/stock_account/models/stock_move_line.py", line 49, in write
    res = super(StockMoveLine, self).write(vals)
  File "/opt/odoo/auto/addons/stock/models/stock_move_line.py", line 373, in write
    Quant._update_reserved_quantity(ml.product_id, ml.location_id, -ml.product_qty, lot_id=ml.lot_id, package_id=ml.package_id, owner_id=ml.owner_id, strict=True)
  File "/opt/odoo/auto/addons/stock/models/stock_quant.py", line 685, in _update_reserved_quantity
    raise UserError(_('It is not possible to unreserve more products of %s than you have in stock.', product_id.display_name))
odoo.exceptions.UserError: It is not possible to unreserve more products of Acoustic Magic Bloc than you have in stock.

```

cc @ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
In addition, if for some reason the correct quant is reserved but then we try to cancel the repair order you may end with this error, because the system is trying to unreserve the incorrect quant again:
image

**Review by LoisRForgeFlow — APPROVED** [review]
Code review :+1:

**Review by JordiMForgeFlow — APPROVED** [review]
code review LGTM

**Pull request merged**
