### PR TITLE
[17.0][ADD] repair_duration: New module repair_duration

### PR DESCRIPTION
**Pull request by ppyczko**
This module adds a Repair Duration field to the repair order form, allowing users to specify the time taken for a repair. The field is only editable when the repair order status is Under Repair, ensuring that the duration can only be adjusted during the repair process.

cc https://github.com/APSL 161660

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @BernatObrador please review

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat and code review

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat and code review

**Review by BernatObrador — APPROVED** [review]
LGTM

**Review by peluko00 — COMMENTED** [review]
Can you rename the module as repair_timesheet and do with timesheets?

**Comment by ppyczko** [comment]
Sure, will do, thank you @peluko00!

**Pull request closed without merging**
